# Managed by Quickshell
general {
    lock_cmd = pidof hyprlock || hyprlock -c '/home/ekrem/.config/hypr/lock/hyprlock.conf'
    unlock_cmd = killall hyprlock
    before_sleep_cmd = pidof hyprlock || hyprlock -c '/home/ekrem/.config/hypr/lock/hyprlock.conf'
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = true
    ignore_systemd_inhibit = true
}

listener {
    timeout = 1800
    on-timeout = pidof hyprlock || hyprlock -c '/home/ekrem/.config/hypr/lock/hyprlock.conf'
    ignore_inhibit = true
}

listener {
    timeout = 1860
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 2220
    on-timeout = systemctl suspend
}
