# Managed by Quickshell
general {
    disable_loading_bar = false
}

background {
    path = /home/ekrem/Pictures/wallpapers/Linux-user-Room.png
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    rounding = -1
    fade_on_empty = true
    placeholder_text = <span foreground="##cba6f7">Enter Password</span>
    font_size = 24
    shadow_passes = 0
    halign = center
    valign = center
}

label {
    monitor =
    text = <span foreground="##ffffff" size="xx-large">SCREEN LOCKED</span>
    font_size = 30
    halign = center
    valign = top
    text_align = center
    pos = 0, 100
}
