# ~/.config/hypr/hyprlock.conf
# UltraMode'un En Basit hyprlock Config'i

general {
    disable_loading_bar = false
    # disable_failure_text = true # Şifre yanlış girilince yazı gösterme
}

background {
    path = ~/.config/hypr/lock/wallpaper.jpg
                                              # Eğer yoksa, geçici olarak burayı yorum satırı yap (# koy)
                                              # veya boş bırak, sadece rengi kullansın.
    # color = rgba(25, 20, 20, 0.8) # Eğer resim istemiyorsan, bu satırı kullanabilirsin
}

input-field {
    monitor =
    size = 200, 50
    outline_thickness = 3
    rounding = -1 # Köşeleri yuvarla
    fade_on_empty = true
    placeholder_text = <span foreground="##cba6f7">Şifreni Gir, Kankam!</span>
    font_size = 24
    shadow_passes = 0
    halign = center
    valign = center
}

label {
    monitor =
    text = <span foreground="##ffffff" size="xx-large">EKREM'İN DÜNYASI KİLİTLENDİ</span>
    font_size = 36
    halign = center
    valign = top
    text_align = center
    pos = 0, 100
}
