exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle -c ~/.config/hypr/lock/hypridle.conf

exec-once = nm-applet --indicator
exec-once = quickshell
exec-once = swww-daemon

exec-once = dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = QT_QPA_PLATFORM=xcb keepassxc /home/ekrem/m2/Passwords.kdbx --keyfile /home/ekrem/m2/ekom
