windowrule {
  name = windowrule-2
  opacity = 1.0 1.0
  match:class = ^(kitty)$
}

windowrule {
  name = kittyfloat-opacity
  opacity = 1.0 1.0
  match:class = ^(kittyfloat)$
}

windowrule {
  name = kittyfloat-main
  float = on
  size = (monitor_w*0.4) (monitor_h*0.6)
  center = on
  match:class = ^(kittyfloat)$
}

windowrule {
  name = windowrule-1b
  float = on
  size = (monitor_w*0.4) (monitor_h*0.6)
  center = on
  match:class = ^(kitty)$
}

windowrule {
  name = windowrule-1
  float = on
  size = (monitor_w*0.4) (monitor_h*0.6)
  center = on
  match:initial_class = ^(kitty)$
}

windowrule {
  name = windowrule-1
  float = on
  size = (monitor_w*0.4) (monitor_h*0.6)
  center = on
  match:initial_class = ^(Picture-in-Picture)$
}

windowrule {
  name = smallWindow
  match:class = ^(pavucontrol|org\.pulseaudio\.pavucontrol|nm-connection-editor|Zotero)$
  float = on
  center = on
  size = (monitor_w*0.45) (monitor_h*0.45)
}

windowrule {
  name = pictureInPicture-SecondMonitor
  match:title = ^([Pp]icture[-\s]?[Ii]n[-\s]?[Pp]icture)(.*)$
  float = on
  pin = on
  size = 1200 675
  move = 2860 300
}
