# Managed by Quickshell
general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd = killall hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = true
    ignore_systemd_inhibit = true
}

listener {
    timeout = 60
    on-timeout = brightnessctl set $(( $(brightnessctl g) / 2 ))
    on-resume = brightnessctl set $(( $(brightnessctl g) * 2 ))
}

listener {
    timeout = 120
    on-timeout = loginctl lock-session
}

listener {
    timeout = 2400
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 6180
    on-timeout = systemctl suspend
}
